# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XCkalfULOul8e8kgBP7r6P8ybszB5Edy
"""

# config.py

import streamlit as st

class Config:
    """Application configuration"""

    # Page configuration
    PAGE_CONFIG = {
        "page_title": "Drilling Workover Data Processor",
        "page_icon": "🛢️",
        "layout": "wide"
    }

    # Column mappings for display
    COLUMN_MAPPING = {
        "waktu_mulai": "Waktu Mulai",
        "waktu_akhir": "Waktu Akhir",
        "durasi_jam": "Durasi (Jam)",
        "peralatan_deskripsi": "Peralatan Utama & Deskripsi Operasi",
        "interval_kedalaman": "Interval/Kedalaman Operasi",
        "kondisi_hasil": "Kondisi Awal/Hasil Utama"
    }

    # Keywords for operation classification
    OPERATION_KEYWORDS = {
        'bailing': ['BAILING', 'B.O.S'],
        'swabbing': ['SWAB'],
        'running': ['RIH', 'RUN'],
        'pulling': ['POH', 'PULL'],
        'makeup': ['M/U', 'MAKE UP'],
        'rigup': ['N/U'],
        'rigdown': ['N/D'],
        'waiting': ['W/O', 'WAIT']
    }

    # Equipment keywords
    EQUIPMENT_KEYWORDS = [
        'SAND PUMP', 'M.SHOE', 'TBG', 'SWAB', 'OE', 'OET',
        'PUP', 'LINE', 'TOOL', 'PUMP', 'CASING', 'DRILL PIPE'
    ]

    @staticmethod
    def init_session_state():
        """Initialize session state variables"""
        if "processed_data" not in st.session_state:
            st.session_state.processed_data = []
        if "raw_input" not in st.session_state:
            st.session_state.raw_input = ""
        if "api_key" not in st.session_state:
            st.session_state.api_key = ""
        if "gemini_configured" not in st.session_state:
            st.session_state.gemini_configured = False