# -*- coding: utf-8 -*-
"""data_processor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XCkalfULOul8e8kgBP7r6P8ybszB5Edy
"""

# processors/data_processor.py

import re
from typing import List, Dict
from ..parsers.ai_parser import AIParser
from ..parsers.rule_parser import RuleParser

class DataProcessor:
    """Main data processing class"""

    def __init__(self, use_ai: bool = False, api_key: str = None):
        self.use_ai = use_ai
        self.api_key = api_key
        self.ai_parser = AIParser(api_key) if use_ai and api_key else None
        self.rule_parser = RuleParser()

    def process_raw_data(self, raw_text: str) -> List[Dict]:
        """Process raw text data into structured format"""
        rows = self._parse_raw_input_to_rows(raw_text)
        processed_rows = []

        for row in rows:
            if self.use_ai and self.ai_parser:
                try:
                    parsed_data = self.ai_parser.parse_row(row)
                except:
                    parsed_data = self.rule_parser.parse_row(row)
            else:
                parsed_data = self.rule_parser.parse_row(row)

            if parsed_data:
                processed_rows.append(parsed_data)

        return processed_rows

    def _parse_raw_input_to_rows(self, raw_text: str) -> List[str]:
        """Parse raw text into individual rows"""
        rows = []
        lines = raw_text.strip().split('\n')

        current_row = []
        for line in lines:
            line = line.strip()
            if not line:
                continue

            # Check if line starts with time pattern
            if re.match(r'^\d{1,2}:\d{2}', line):
                if current_row:
                    rows.append(' '.join(current_row))
                current_row = [line]
            else:
                current_row.append(line)

        if current_row:
            rows.append(' '.join(current_row))

        return rows